---
- name: Common tasks FTW
  hosts: all
  become: yes
  pre_tasks:
    - name: Set hostname
      hostname: name={{inventory_hostname}}

- name: panda base services
  hosts: base
  become: yes
  roles:
    - { role: nodejs, tags: nodejs }
    - { role: apps, tags: apps }
